[tool.poetry]
name = "model"
version = "0.1.0"
description = ""
authors = ["ohke <kenta1988@gmail.com>"]

[tool.poetry.dependencies]
torch = "^1.11"
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
